version: '3.7'

services:
  nameindex:
    image: ghcr.io/biodiversitydata-se/ala-name-matching-index:1.0.0
    volumes:
      - data_nameindex:/data/lucene/namematching

  namematching-service:
    image: sbdi/ala-namematching-service-dev
    build:
      context: .
      no_cache: true
    environment:
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k
    volumes:
      - data_nameindex:/data/lucene/namematching
      - ./sbdi/data/config/namematching-service-config.yml:/data/ala-namematching-service/config/namematching-service-config.yml
    ports:
      - 9179:9179
      - 9180:9180

volumes:
  data_nameindex:
