version: '3.8'

services:

  namematching-service:
    image: sbdi/ala-namematching-service-dev
    build:
      context: .
      no_cache: true
    environment:
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k
    volumes:
      - data_nameindex:/data/lucene/namematching
      - ./sbdi/data/config/namematching-service-config.yml:/data/ala-namematching-service/config/namematching-service-config.yml
    ports:
      - 9179:9179
      - 9180:9180

volumes:
  data_nameindex:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/lucene/namematching"
